name: Update Stdlib Manifest

on:
  workflow_dispatch:
  schedule:
    - cron: '19 3 * * 4'

jobs:
  update_stdlib_manifest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: julia-actions/setup-julia@5c9647d97b78a5debe5164e9eec09d653d29bd71 # v2.6.1
        with:
          version: 'nightly'
      - uses: julia-actions/cache@824243901fb567ccb490b0d0e2483ccecde46834 # v2.0.5
      - name: 'Update stdlib manifest'
        shell: julia --project=stdlib --color=yes {0}
        run: |
          using Pkg
          Pkg.Registry.add("General")
          Pkg.resolve()
      - uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          branch: 'gha/update-stdlib-manifest'
          commit-message: 'Update stdlib/Manifest.toml'
          title: 'Update stdlib/Manifest.toml'
